//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectronicShopManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItem
    {
        public int OrderId { get; set; }
        public int ProdId { get; set; }
        public Nullable<decimal> PriceAtPurchase { get; set; }
        public Nullable<int> OrderQty { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
    }
}
